export const DEFAULT_MOCK_OBRAS = [
  {
    id_pncp: "2026-SP-001",
    numero_controle_pncp: "18236120000158-1-000042/2026",
    orgao: "Prefeitura Municipal de São José dos Campos - SP",
    municipio: "São José dos Campos",
    uf: "SP",
    objeto: "Contratação de empresa especializada de engenharia para execução das obras de duplicação e pavimentação asfáltica da Av. Parque Tecnológico, incluindo drenagem pluvial, ciclovia e sinalização viária completa.",
    modalidade: "Concorrência Eletrônica (4)",
    valor_estimado: 14850000.0,
    data_publicacao: "2026-08-16T10:30:00",
    fonte: "MOCK_SANDBOX",
    link_pncp: "https://pncp.gov.br/app/editais/18236120000158/2026/000042",
    categoria: "Infraestrutura Viária",
    prazo_meses: 18,
    status_obra: "Aberto para Propostas",
  },
  {
    id_pncp: "2026-MG-002",
    numero_controle_pncp: "18431312000134-1-000115/2026",
    orgao: "Secretaria de Estado de Infraestrutura e Mobilidade de Minas Gerais (SEINFRA)",
    municipio: "Belo Horizonte",
    uf: "MG",
    objeto: "Obras civis para reforma geral e ampliação do Hospital Regional do Vale do Aço, contemplando novo bloco cirúrgico, 40 leitos de UTI, subestação de energia e climatização hospitalar central.",
    modalidade: "Concorrência Eletrônica (4)",
    valor_estimado: 32400000.0,
    data_publicacao: "2026-08-15T14:15:00",
    fonte: "MOCK_SANDBOX",
    link_pncp: "https://pncp.gov.br/app/editais/18431312000134/2026/000115",
    categoria: "Edificações de Saúde",
    prazo_meses: 24,
    status_obra: "Publicado",
  },
  {
    id_pncp: "2026-PR-003",
    numero_controle_pncp: "76416940000128-1-000088/2026",
    orgao: "Prefeitura Municipal de Maringá - PR",
    municipio: "Maringá",
    uf: "PR",
    objeto: "Construção de Centro Municipal de Educação Infantil (CMEI) de 12 salas no Jardim Alvorada, com quadra poliesportiva coberta, energia solar fotovoltaica e acessibilidade universal (NBR 9050).",
    modalidade: "Concorrência Eletrônica (4)",
    valor_estimado: 7650000.0,
    data_publicacao: "2026-08-14T09:00:00",
    fonte: "MOCK_SANDBOX",
    link_pncp: "https://pncp.gov.br/app/editais/76416940000128/2026/000088",
    categoria: "Educação",
    prazo_meses: 12,
    status_obra: "Fase de Habilitação",
  },
  {
    id_pncp: "2026-BA-004",
    numero_controle_pncp: "13927801000149-1-000021/2026",
    orgao: "Companhia de Engenharia Hídrica e de Saneamento da Bahia (CERB)",
    municipio: "Feira de Santana",
    uf: "BA",
    objeto: "Implantação de Sistema Integrado de Abastecimento de Água Tratada (SIAA), incluindo adutora de 34km em PEAD, 2 reservatórios apoiados e 1.200 ligações domiciliares.",
    modalidade: "Pregão Eletrônico (6)",
    valor_estimado: 19800000.0,
    data_publicacao: "2026-08-13T16:45:00",
    fonte: "MOCK_SANDBOX",
    link_pncp: "https://pncp.gov.br/app/editais/13927801000149/2026/000021",
    categoria: "Saneamento & Hídrica",
    prazo_meses: 15,
    status_obra: "Julgamento de Propostas",
  },
  {
    id_pncp: "2026-CE-005",
    numero_controle_pncp: "07206048000187-1-000009/2026",
    orgao: "Superintendência de Obras Públicas do Estado do Ceará (SOP)",
    municipio: "Fortaleza",
    uf: "CE",
    objeto: "Execução de obras de contenção de encostas e contenção marítima com enrocamento de pedras e muros de gabião em trecho crítico da orla leste.",
    modalidade: "Concorrência Eletrônica (4)",
    valor_estimado: 26300000.0,
    data_publicacao: "2026-08-12T11:20:00",
    fonte: "MOCK_SANDBOX",
    link_pncp: "https://pncp.gov.br/app/editais/07206048000187/2026/000009",
    categoria: "Contenção & Geotecnia",
    prazo_meses: 20,
    status_obra: "Aberto",
  },
  {
    id_pncp: "2026-RS-006",
    numero_controle_pncp: "92963560000160-1-000037/2026",
    orgao: "Departamento Autônomo de Estradas de Rodagem (DAER-RS)",
    municipio: "Caxias do Sul",
    uf: "RS",
    objeto: "Construção de ponte em concreto armado e protendido de 140m sobre o Rio das Antas, com pilares reforçados contra cheias e acessos rodoviários pavimentados.",
    modalidade: "Concorrência Eletrônica (4)",
    valor_estimado: 41200000.0,
    data_publicacao: "2026-08-11T08:50:00",
    fonte: "MOCK_SANDBOX",
    link_pncp: "https://pncp.gov.br/app/editais/92963560000160/2026/000037",
    categoria: "Pontes e Viadutos",
    prazo_meses: 22,
    status_obra: "Em Análise Técnica",
  },
  {
    id_pncp: "2026-GO-007",
    numero_controle_pncp: "01234567000199-1-000012/2026",
    orgao: "Prefeitura Municipal de Anápolis - GO",
    municipio: "Anápolis",
    uf: "GO",
    objeto: "Modernização do parque de iluminação pública municipal com fornecimento e instalação de 8.500 luminárias LED de alta eficiência e sistema de telegestão inteligente.",
    modalidade: "Pregão Eletrônico (6)",
    valor_estimado: 11950000.0,
    data_publicacao: "2026-08-10T15:10:00",
    fonte: "MOCK_SANDBOX",
    link_pncp: "https://pncp.gov.br/app/editais/01234567000199/2026/000012",
    categoria: "Elétrica & Smart City",
    prazo_meses: 10,
    status_obra: "Homologada",
  },
  {
    id_pncp: "2026-SC-008",
    numero_controle_pncp: "83102345000111-1-000005/2026",
    orgao: "Prefeitura Municipal de Joinville - SC",
    municipio: "Joinville",
    uf: "SC",
    objeto: "Serviços emergenciais de desassoreamento de rios urbanos e dragagem mecanizada de canais para prevenção de inundações e drenagem de bacias hidrográficas.",
    modalidade: "Dispensa de Licitação (8)",
    valor_estimado: 4850000.0,
    data_publicacao: "2026-08-09T13:00:00",
    fonte: "MOCK_SANDBOX",
    link_pncp: "https://pncp.gov.br/app/editais/83102345000111/2026/000005",
    categoria: "Drenagem Urbana",
    prazo_meses: 6,
    status_obra: "Execução Imediata",
  },
];

export const MOCK_SCENARIOS = {
  completo: {
    nome: "Padrão (Diversas Obras e Modalidades)",
    descricao: "8 obras com variedade de valores (R$ 4.8M a R$ 41.2M), estados (SP, MG, PR, BA, CE, RS, GO, SC) e modalidades.",
    dados: DEFAULT_MOCK_OBRAS,
    statusInfo: {
      status: "sucesso_mock",
      mensagem: "Cenário Sandbox: 8 obras simuladas carregadas.",
      total: 8,
    },
  },
  grandesObras: {
    nome: "Mega Obras (Acima de R$ 20 Milhões)",
    descricao: "Filtro voltado a construtoras de grande porte com licitações de pontes, hospitais e rodovias.",
    dados: DEFAULT_MOCK_OBRAS.filter((o) => o.valor_estimado >= 20000000),
    statusInfo: {
      status: "sucesso_mock",
      mensagem: "Cenário Sandbox: 4 mega licitações simuladas.",
      total: 4,
    },
  },
  mockDev: {
    nome: "Ambiente Simulado (Modo Mock / Offline)",
    descricao: "Simulação de resposta com dados gerados sinteticamente para testes locais rápidos.",
    dados: DEFAULT_MOCK_OBRAS.map((o) => ({ ...o, fonte: "MOCK_SANDBOX" })),
    statusInfo: {
      status: "sucesso_mock",
      mensagem: "Modo mock ativado: 8 licitações simuladas para validação de layout.",
      total: 8,
    },
  },
  vazio: {
    nome: "Sem Resultados (Nenhuma Obra)",
    descricao: "Simula quando a busca não encontra nenhuma licitação para os critérios informados.",
    dados: [],
    statusInfo: {
      status: "aviso",
      mensagem: "Nenhuma licitação encontrada no PNCP para o período e modalidade selecionados.",
      total: 0,
    },
  },
  erro: {
    nome: "Erro de Conexão com API",
    descricao: "Simula falha ou indisponibilidade temporária do portal PNCP ou do backend FastAPI.",
    dados: [],
    statusInfo: {
      status: "erro_conexao",
      mensagem: "Erro ao conectar com a API PNCP: tempo limite esgotado (Timeout 504).",
      total: 0,
    },
  },
};
